flowchart LR

gateway{Gateway}
groot{Groot}
rocket{Rocket}
heimdall{Heimdall}
ultron{Ultron}
hulk{Hulk}
ctb-connector{CTB Connector}
ia{IA}

gateway-db[(Gateway DB)]
groot-db[(Groot DB)]
rocket-db[(Rocket DB)]
heimdall-db[(Heimdall DB)]

subgraph CDC
  direction LR
  ia -->Widget-UI
end

ia <-- WSS --> gateway
ia -- HTTP --> gateway
gateway --> HTTP-Request-Queue
gateway --> rocket-Request-Queue
gateway <--> gateway-db
gateway -- WS --> heimdall
rocket-Request-Queue <--> groot
HTTP-Request-Queue --> groot
rocket-Job-Complete-Queue --> groot
groot <--> groot-db
groot --> Ultron-Request-Queue
groot --> Notification-Queue
rocket <--> rocket-db
rocket-Request-Queue --> rocket
rocket-Main-Queue --> rocket
rocket --> CloudFront
rocket --> S3
rocket --> rocket-Job-Complete-Queue
rocket -- HTTP --> groot
heimdall --> heimdall-db
heimdall -- HTTP --> groot
Notification-Queue --> heimdall
Ultron-Request-Queue --> rocket-Main-Queue
Ultron-Request-Queue --> ultron
ultron --> Ultron-Response-Queue
Ultron-Request-Queue --> Ultron-Response-Queue
groot --> CTB-Prediction-Request-Queue
ultron <-- gRPC --> hulk 
hulk  <-- gRPC --> Tensorflow-Server1
hulk  --> id5[(Mysql)]
ctb-connector <-- gRPC --> Tensorflow-Server2
ctb-connector --> rocket-Main-Queue
CTB-Prediction-Request-Queue --> ctb-connector
ctb-connector --> Ultron-Response-Queue