name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@annaliseai'
      - if: steps.get_branch.outputs.branch == 'main'
        run: yarn && ./scripts/generateSVGs.sh
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
           -s
           -o
           ./documents/OPT-SW-025.docx
           ./documents/OPT-SW-025.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          
