name: Simple Usage

on: push

jobs:
  markdown-to-pdf:
    name: Convert Markdown documents to PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn ts-node ./scripts/extract-diagrams
      - run: yarn mmdc -i ./diagrams/test.md -o diagrams/test.svg
      - run: yarn md-to-pdf ./new-test.md
      - uses: actions/upload-artifact@v3
        with:
            name: new-test.pdf
            path: ./new-test.pdf