name: Simple Usage

on: push

jobs:
  markdown-to-pdf:
    name: Convert Markdown documents to PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn ts-node ./scripts/extract-diagrams
      - run: yarn md-to-pdf ./test.md
      - uses: actions/upload-artifact@v3
        with:
            name: test.pdf
            path: ./test.pdf